app:
  name: sitegate-admin
port: 3040
session: 
  secret: sitegate-admin
  collection: sessions
sitegate:
  domain: https://account.sitegatedev.com:3000
  clientId: AoMFA3Z1XvwtLj9558cC
  clientSecret: X5iKRIPQICq0Hye2WqQX3GJWWR2AXD1nXwEfm6tq
  callbackURL: https://localhost:3040/auth/sitegate/callback
amqp:
  login: guest
  password: guest
  address: localhost
  port: 5672